---
- name: Configure web server(s)
  hosts: webservers
  sudo: yes
  vars_files:
  - [ "secrets.yml", "secrets.minimal.yml" ]
  vars:
    docroot: /vagrant_data/_site
    backendroot: /vagrant_data/src/drc-backend
    server_name: localhost
    common_region: IAD
    mailgun_domain: "{{ dev_mailgun_domain }}"
    sponsorship_notification_email: "{{ dev_sponsorship_notification_email }}"
    sponsorship_container: "{{ dev_sponsorship_container }}"
  roles:
    - role: webserver
      content_owner: vagrant
    - role: bennojoy.nginx
      nginx_http_params:
        client_max_body_size: 50m
        sendfile: "on"
        access_log: /var/log/nginx/access.log
        server_tokens: "off"
        more_set_headers: '"Server: Nintendo WiiOS; Server 1.up"'
      nginx_sites:
      - server:
          gzip_static: "on"
          file_name: developer.rackspace.com
          listen: 80
          server_name: "{{ server_name }}"
          root: "{{ docroot }}"
          location1:
            name: /api
            proxy_pass: http://127.0.0.1:8111
          location2:
            name: /blog/index.html
          location3:
            name: /blog
            rewrite: "^/blog/([^/]+)\\.html$ /blog/$1/ permanent"
          location4:
            name: /devtrial
            rewrite: "^/devtrial /signup/ permanent"
    - jekyll
    - sphinx
    - dev

- name: Launch the backend form submission script
  hosts: webservers
  vars:
    docroot: /vagrant_data/_site
    backendroot: /vagrant_data/src/drc-backend
    sourceroot: /vagrant_data/
  roles:
    - role: content
      srcroot: /vagrant_data
      foreverargs: --watch --watchDirectory {{ backendroot }}
