---
- name: Configure web server(s)
  hosts: webservers
  sudo: yes
  vars:
    docroot: /vagrant_data/_site
    backendroot: /var/webapp/sponsorship-form
    sourceroot: /vagrant_data/
    server_name: localhost
  roles:
    - webserver
    - role: bennojoy.nginx
      nginx_http_params:
        sendfile: "on"
        access_log: /var/log/nginx/access.log
      nginx_sites:
      - server:
          file_name: developer.rackspace.com
          listen: 80
          server_name: "{{ server_name }}"
          root: "{{ docroot }}"
          location1:
            name: /api
            proxy_pass: http://127.0.0.1:8111
    - jekyll
    - sphinx
    - dev
