---
- name: Configure web server(s)
  hosts: webservers
  sudo: yes
  vars_files:
  - vars.yml
  - [ "secrets.yml", "secrets.minimal.yml" ]
  vars:
    docroot: /vagrant_data/_site
    backendroot: /vagrant_data/src/drc-backend
    server_name: localhost
    common_region: IAD
    mailgun_domain: "{{ dev_mailgun_domain }}"
    sponsorship_notification_email: "{{ dev_sponsorship_notification_email }}"
    sponsorship_container: "{{ dev_sponsorship_container }}"
    mongodb_connection_url: "{{ dev_mongodb_connection_url }}"
  roles:
    - role: webserver
      content_owner: vagrant
    - bennojoy.nginx
    - jekyll
    - sphinx
    - editors
    - dev

- name: Launch the backend form submission script
  hosts: webservers
  vars:
    docroot: /vagrant_data/_site
    backendroot: /vagrant_data/src/drc-backend
    sourceroot: /vagrant_data/
  roles:
    - role: content
      srcroot: /vagrant_data
      foreverargs: --watch --watchDirectory {{ backendroot }}
