---
- name: Provision production web setup
  hosts: local
  connection: local
  tasks:

    - name: Provision production web load balancer
      rax_clb:
        credentials: ~/.rackspace_cloud_credentials
        name: "prod_{{ server_name }}"
        port: 80
        protocol: HTTP
        algorithm: ROUND_ROBIN
        type: PUBLIC
        timeout: 30
        region: "{{ lookup('env', 'RAX_REGION') | upper }}"
        wait: yes
        state: present
      register: clb

    - name: Provision 2 production web servers
      rax:
        credentials: ~/.rackspace_cloud_credentials
        name: "prod_webserver_%01d"
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin
        networks:
          - public
          - private
        region: "{{ lookup('env', 'RAX_REGION') | upper }}"
        state: present
        count: 2
        exact_count: yes
        group: prod_webservers
        wait: yes
        key_name: drg
      register: rax

    - name: Add web servers to load balancer
      rax_clb_nodes:
        credentials: ~/.rackspace_cloud_credentials
        load_balancer_id: "{{ clb.balancer.id }}"
        address: "{{ item.rax_networks.private|first }}"
        port: 80
        condition: enabled
        type: primary
        wait: yes
        region: "{{ lookup('env', 'RAX_REGION') | upper }}"
      with_items: rax.success
      when: rax.action == 'create'

    - name: Add web servers to prod_webservers host group
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        groupname: prod_webservers
      with_items: rax.success
      when: rax.action == 'create'

- name: Configure web server(s)
  hosts: prod_webservers
  remote_user: root
  vars_files:
  - ip_access.yml
  - paths.yml
  - secrets.yml
  roles:
    - webserver
    - lockboxweb
    - role: bennojoy.nginx
      nginx_http_params:
        sendfile: "on"
        access_log: /var/log/nginx/access.log
      nginx_sites:
      - server:
          file_name: developer.rackspace.com
          listen: 80
          server_name: "{{ server_name }}"
          root: "{{ docroot }}"
          gzip: "on"
          gzip_min_length: 1400
          gzip_types: text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript
          gzip_vary: "on"
          gzip_proxied: any
          location1:
            name: /api
            proxy_pass: http://127.0.0.1:8111
