# Master playbook to provision and bootstrap all production and staging servers.
---
- name: Check prerequisites and fail fast.
  hosts: local
  connection: local
  gather_facts: no
  tasks:

  - name: Ensure that exactly one monitoring setup is active.
    fail:
      msg: |
        Invalid monitoring setup. You must specify exactly one monitoring target, or disable
        monitoring entirely.

        Choices:

        # Disable monitoring
        --skip-tags monitoring

        # PagerDuty, using credentials from secrets(.vault).yml
        --extra-vars="mon_pagerduty=true"

        # Email, using a provided email address
        --extra-vars="mon_email=me@mydomain.com"
    when: >
      (mon_pagerduty is not defined and mon_email is not defined) or
      (mon_pagerduty is defined and mon_email is defined)
    tags: ["monitoring"]

- include: prod_web.yml server_name=developer.rackspace.com tags=production

- include: staging_web.yml server_name=staging.developer.rackspace.com tags=staging

- include: jenkins.yml tags=jenkins

- include: monitoring.yml tags=monitoring
