---
# Paths that should be common across playbooks.

# Rackspace region in which the CDN and sponsorship form upload containers should be created.
common_region: IAD

# Destination container for production static assets.
production_container: drc-static-prod

# Destination container for staging static assets.
staging_container: drc-static-staging

# TTL value for CDN containers.
cdn_ttl: 31536000
