#!/usr/bin/env python
#
# Template a local _config.yml.

import os
from jinja2 import Environment, FileSystemLoader

root = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
template_dir = os.path.join(root, 'deploy', 'templates')
output_path = os.path.join(root, 'src', 'site_source', '_config.yml')

env = Environment(loader=FileSystemLoader(template_dir))
template = env.get_template('_config.yml.j2')

with open(output_path, 'w') as outf:
    outf.write(template.render(
        ansible_managed='generated with script/localconf',
        compress_assets=False
    ))
