#!/bin/bash
#
# Persist deploy/secrets-clear-text.yml as deploy/secrets.vault.yml.

ROOT=$(cd $(dirname $0)/..; pwd)

if [ ! -e ${ROOT}/deploy/secrets-clear-text.yml ]; then
  echo "[lock] secrets-clear-text.yml does not exist!"
  exit 1
fi

cp ${ROOT}/deploy/secrets-clear-text.yml ${ROOT}/deploy/secrets.vault.yml
ansible-vault encrypt ${ROOT}/deploy/secrets.vault.yml
