# Common settings shared by all Jekyll configurations.

name: Rackspace Developer Portal
url: http://developer.rackspace.com

markdown: redcarpet
redcarpet:
  extensions: [ "tables" ]
highlighter: pygments
paginate: 10
relative_permalinks: true
permalink: /blog/:title
paginate_path: /blog/page:num
recent_posts: 5
excerpt_separator: "<!-- more -->"
subscribe_rss: /atom.xml

# Disqus config
disqus_short_name: devopsrackspace
disqus_show_comment_count: false

# Blog categories
category_dir: blog/categories

# jekyll-assets plugin configuration.
assets:
  sources:
  - _assets/img
  - _assets/fonts
  - _assets/js
  - _assets/css
